name: chill-chaser-server

services:
  db:
    extends:
      file: docker-db-service.yml
      service: db
    environment: 
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  migrate:
    image: joms1337/chill-chaser-migrations:latest
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db_passfile
  api:
    image: joms1337/chill-chaser-web:latest
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    secrets:
      - db_passfile
    ports:
      - 2345:8080
    volumes:
      - ~/apps/chill-chaser/:/root/.aspnet/DataProtection-Keys
    restart: always
    environment:
      - CC_IMAGE_VERSION=0.0.0
secrets:
  db_password:
    file: ./db_password.txt
  db_passfile:
    file: ./db_passfile.txt
  
    
