name: build-test

on: [ push ]

jobs:
  test-dev-environment:
    name: Test in development environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Start docker compose environment
        uses: gacts/run-and-post-run@v1
        with:
          run: docker compose -f docker-compose.dev.yml up -d
          post: docker compose -f docker-compose.dev.yml down
      - name: Wait for postgres to be ready
        run: sleep 30
      - name: Run migrations
        run: dotnet ef update --project ChillChaser
      - name: Test in non integrated environment
        run: dotnet test
      - name: Shutdown docker
        run: docker compose -f docker-compose.dev.yml down
  test-prod-environment:
    name: Test in production environemnt
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.web
          context: .
          push: true
          tags: localhost:5000/name/web:latest
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.migration
          context: .
          push: true
          tags: localhost:5000/name/migrations:latest
      
      - name: Start docker compose environment
        uses: gacts/run-and-post-run@v1
        with:
          run: |
            echo "password" > db_password.txt
            echo "db:5432:chillchaser_db:chillchaser_user:password" > db_passfile.txt 
            docker compose up -d
          post: docker compose down
      - name: Run E2E tests in integrated environment
        env: 
          INTEGRATED_ENVIRONMENT: yes
        run: 'dotnet test'
      - name: Shut down docker
        run: docker compose down
          