name: build-test

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Test in non integrated environment
        run: dotnet test 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.web
          context: .
          push: true
          tags: localhost:5000/name/web:latest
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.migration
          context: .
          push: true
          tags: localhost:5000/name/migrations:latest
      
      - name: Start docker compose environment
        uses: gacts/run-and-post-run@v1
        with:
          run: |
            echo "password" > db_password.txt
            echo "db:5432:chillchaser_db:chillchaser_user:password" > db_passfile.txt 
            docker compose up -d
          post: docker compose down
      - name: Run E2E tests in integrated environment
        env: 
          INTEGRATED_ENVIRONMENT: yes
        run: 'dotnet test --logger:"console;verbosity=detailed"'
      - name: Shut down docker
        run: docker compose down
          