name: Docker
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Match version
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref_name }}
          regex: '^[mw]+([0-9\.]+)$'
      - name: Build and push web
        if: ${{ contains(github.ref_name, 'w')}}
        uses: docker/build-push-action@v5
        with:
          file: ChillChaser/Dockerfile.web
          context: ChillChaser
          push: true
          tags: |
            ${{env.DOCKER_USERNAME}}/${{env.DOCKER_WEB_REPO}}:latest
            ${{env.DOCKER_USERNAME}}/${{env.DOCKER_WEB_REPO}}:${{steps.regex-match.outputs.group1}}
      - name: Build and push migration package
        if: ${{ contains(github.ref_name, 'm') }}
        uses: docker/build-push-action@v5
        with:
          file: ChillChaser/Dockerfile.migration
          context: ChillChaser
          push: true
          tags: |
            ${{env.DOCKER_USERNAME}}/${{env.DOCKER_MIGRATION_REPO}}:latest
            ${{env.DOCKER_USERNAME}}/${{env.DOCKER_MIGRATION_REPO}}:${{steps.regex-match.outputs.group1}}
