name: Docker
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    name: 'Build and publish docker images'
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.web
          push: true
          tags: |
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_WEB_REPO}}:latest
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_WEB_REPO}}:${{ github.ref_name }}
      - name: Build and push migration package
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.migration
          push: true
          tags: |
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_MIGRATION_REPO}}:latest
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_MIGRATION_REPO}}:${{ github.ref_name }}
  release-artifacts:
    permissions:
      contents: write
    name: 'Generate release artifacts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add version to docker-compose
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.services.api.environment[0] = "CC_IMAGE_VERSION=${{ github.ref_name }}"' 'docker-compose.yml'
      - name: Add compose to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docker-compose.yml
          asset_name: docker-compose.yml
          tag: ${{ github.ref }}
