name: Docker
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Add version to docker-compose
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'Dockerfile.web'
          propertyPath: 'services.api.environment[0]'
          value: ${{ github.ref_name }}
          commitChange: false
      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.web
          push: true
          tags: |
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_WEB_REPO}}:latest
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_WEB_REPO}}:${{ github.ref_name }}
      - name: Build and push migration package
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.migration
          push: true
          tags: |
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_MIGRATION_REPO}}:latest
            ${{vars.DOCKER_USERNAME}}/${{vars.DOCKER_MIGRATION_REPO}}:${{ github.ref_name }}
      - name: Add compose to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: docker-compose.yml
          asset_name: docker-compose.yml
          tag: ${{ github.ref }}
